server:
  port: 9529
spring:
  application:
    name: microservicecloud-zuul-gateway

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: gateway.9529.com
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: ysp-microservicecloud
  company.name: www.ysp.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #ignored-services: microservicecloud-dept
  ignored-services: "*" ##屏蔽所有
  prefix: /ysp


